### ISSUE TITLE
Intentar mostrar el campo :3

### ISSUE THREAD

**Issue by bcifuentes** [Ceratoide/CARGAS#6]
Se intentará en estos dias poner o lineas de campo, o intensidad por color, para que se vea en la pantalla

**Comment by bcifuentes** [comment]
Se esta avanzando, pero resulta muy lento

**Comment by jdiegoz** [comment]
Ya se muestra el potencial

**Comment by bcifuentes** [comment]
Ya se puede cambiar entre potencial y pantalla normal

**Comment by bcifuentes** [comment]
Spoiler... Sigue lento :'v

**Comment by bcifuentes** [comment]
YA SE MUESTRA EL POTENCIAL BIEN!!!

**Comment by bcifuentes** [comment]
YA SE MUESTRA EL CAMPO ELECTRICO!!!
