### ISSUE TITLE
Problema con las cargas

### ISSUE THREAD

**Issue by jdiegoz** [Ceratoide/CARGAS#8]
Tal y como esta, por cada carga de campo que hay se genera una sombra en la carga de prueba, en pequeña escala esto no es importante, pero para campos muy complicados esto se puede hacer molesto para el espectador

**Comment by jdiegoz** [comment]
Ahora parece ser que el problema esta peor

**Comment by bcifuentes** [comment]
Solucionado, era un problema en el bucle for
